### ISSUE TITLE
prod-db-backup pipeline is failing

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse-bosh-release#49]
### Description

The `prod-db-backup` has not been running for almost a month.
https://ci.concourse-ci.org/teams/main/pipelines/prod-db-backup

Appears to not be pointing to the `ci` branch.

### Task List
- [x] Fix the pipeline
  - The `ci` resource was pointing to another branch. Pointed it to `master` now.
- [x] Add `prod-db-backup` pipeline to the [reconfigure pipeline](https://github.com/concourse/ci/blob/master/pipelines/reconfigure.yml)
-  [x] Appears to be in there, but name of the file & pipeline name are different. Make them the same: https://github.com/concourse/ci/blob/c3e57184229681d00b811915ddcc27c6bd8a40e7/pipelines/reconfigure.yml#L129-L134
  - Renamed both pipelines to have `prod-db*` in their name.
    - `prod-db-backup`
    - `prod-db-restore-verify`
- [x] Add slack notifications like we have on the concourse pipeline so that way we know when this pipeline fails
- [x] verify secrets for slack notifications are accessible for this pipeline
- [x] Delete the old pipelines:
  - [x] https://ci.concourse-ci.org/teams/main/pipelines/bbr-restore-verify
  - [x] https://ci.concourse-ci.org/teams/main/pipelines/prod-db-backup

Created a branch here: https://github.com/concourse/ci/tree/clean-bbr-test-pipelines
